#name and lore is self explanatory.
# {*} is experience saved in book.
# neededLines are lines that are used to save experience in book. each line must have {*}
expbook:
  name: "{*} experience"
  lore:
    - "Book with {*}"
    - "experience points"
    - "written upon its pages"
  neededLines:
    - "SAVE EXPERIENCE {*}"
    - "EXPERIENCE {*}"
    - "SAVE {*} EXPERIENCE"
    - "SAVE {*} EXP"
    - "ZAPISZ {*} DOŚWIADCZENIA"
    - "ZAPISZ DOŚWIADCZENIE {*}"