name: ExpBook
version: '1.0-SNAPSHOT'
main: com.hemostaza.expbook.Expbook
api-version: '1.21'
commands:
  expbook:
    description: "Show valid lines in book and quil"
    usage: "/expbook"
    aliases: ["eb","expb"]
